Models/ContatoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projetos.CrudMvc.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace crudmvc.Models{

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

}

Models/LoginModel.cs
 namespace Projetos.CrudMvc.Models
{
    public class LoginModel
    {
        public string Login {get; set;}
        public string Senha {get; set;}
    }
}

Models/UsuarioModel.cs
using System;
using Projetos.CrudMvc.Enums;

namespace Projetos.CrudMvc.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
        public PerfilEnum Perfil { get; set; }
        public DateTime DataCadastro { get; set;}
        public DateTime? DataAtualizacao { get; set; }

        public bool SenhaValida(string senha)
        {
            return Senha == senha;
        }
    }
}

Models/UsuarioSemSenhaModel.cs
using System;
using Projetos.CrudMvc.Enums;

namespace Projetos.CrudMvc.Models
{
    public class UsuarioSemSenhaModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public PerfilEnum Perfil { get; set; }
}
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using Projetos.CrudMvc.Models;
using Projetos.CrudMvc.Repositorio;
using System;
using System.Collections;
using System.Linq;
using System.Threading.Tasks;

namespace crudmvc.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }
        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }

        public IActionResult Criar()
        {

            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            _contatoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            _contatoRepositorio.Adicionar(contato);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            _contatoRepositorio.Atualizar(contato);
            return RedirectToAction("Index");
        }


    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using crudmvc.Models;
using Microsoft.Extensions.WebEncoders.Testing;

namespace crudmvc.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LoginController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Projetos.CrudMvc.Models;
using Projetos.CrudMvc.Repositorio;

namespace crudmvc.Controllers
{
    public class LoginController : Controller 
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public LoginController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Entrar(LoginModel loginModel)
        {
           UsuarioModel usuario = _usuarioRepositorio.BuscarPorLogin(loginModel.Login);

            if(usuario != null) {
                if(usuario.SenhaValida(loginModel.Senha))
                {
                 return RedirectToAction("Index","Home");
                }
            }
            return RedirectToAction("Index","Login");
        }
        
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Projetos.CrudMvc.Models;
using Projetos.CrudMvc.Repositorio;
using System;
using System.Collections;
using System.Linq;
using System.Threading.Tasks;

namespace crudmvc.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio; 
        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            _usuarioRepositorio.Adicionar(usuario);
            return RedirectToAction("Index");
        }

        public IActionResult Apagar(int id)
        {
            _usuarioRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuario =_usuarioRepositorio.ListarPorId(id);            
            return View(usuario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario =_usuarioRepositorio.ListarPorId(id);            
            return View(usuario);
        }

        [HttpPost]
        public IActionResult Alterar(UsuarioSemSenhaModel usuarioSemSenhaModel)
        {
            UsuarioModel usuario = null;
            usuario = new UsuarioModel()
            {
                Id = usuarioSemSenhaModel.Id,
                Nome = usuarioSemSenhaModel.Nome,
                Login = usuarioSemSenhaModel.Login,
                Email = usuarioSemSenhaModel.Email,
                Perfil = usuarioSemSenhaModel.Perfil
            };

            usuario = _usuarioRepositorio.Atualizar(usuario);
            return RedirectToAction("Index");
        }
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@using Projetos.CrudMvc.Models;
@using crudmvc.Controllers;
@model ContatoModel;

@{
    ViewData["Title"] = "Confirmação apagar o contato";
}



<div class="text-center">
    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a> 

Views/Contato/Criar.cshtml
@using Projetos.CrudMvc.Models
@model ContatoModel;
@{
    ViewData["Title"] = "Criar Contato";
}

<div class="text-center">

    <h1>Cadastrar Contato</h1>

    <form asp-controller="Contato" asp-action="Criar" method="post">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        </div>
        
        <div class="form-group">
            <label for="Email">E-mail</label>
            <input type="text" asp-for="Email"class="form-control" placeholder="Digite o e-mail do contato">
        </div>

        <div class="form-group">
            <label for="Celular">Celular</label>
            <input type="text" asp-for="Celular"class="form-control celular" placeholder="Digite o celular do contato">
        </div>
        
        <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
        <a class="btn btn-secondary mt-2" asp-controller="Contato" asp-action="Index" role="button">Voltar</a> 
        
    </form>

</div>

Views/Contato/Editar.cshtml
@using Projetos.CrudMvc.Models;
@model ContatoModel;
@{
    ViewData["Title"] = "Editar Contato";
}

<div class="text-center">

    <h1>Editar Contato</h1>

    <form asp-controller="Contato" asp-action="Alterar" method="post">

        <input type="hidden" asp-for="Id" />
         <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        </div>
        
        <div class="form-group">
            <label for="Email">E-mail</label>
            <input type="text" asp-for="Email"class="form-control" placeholder="Digite o e-mail do contato">
        </div>

        <div class="form-group">
            <label for="Celular">Celular</label>
            <input type="text" asp-for="Celular"class="form-control celular" placeholder="Digite o celular do contato">
        </div>
        
        <button type="submit" class="btn btn-primary mt-2">Alterar</button>
        <a class="btn btn-secondary mt-2" asp-controller="Contato" asp-action="Index" role="button">Voltar</a> 

    </form>

</div>

Views/Contato/Index.cshtml
@using Projetos.CrudMvc.Models;
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model List<ContatoModel>;
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar Novo Contato</a>
    </div>
    <br>


    <h1>Listagem de contatos</h1>

    <table class="table" id="table-contatos">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col">Botões</th>
            </tr>
        </thead>

        <tbody>
            @if (Model != null && Model.Any()){
                int cont = 0;
                foreach (ContatoModel contato in Model)
                {
                    cont ++; 
                    <tr>
                    <th scope="row">@cont</th>
                    <td>@contato.Nome</td>
                    <td>@contato.Email</td>
                    <td>@contato.Celular</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-primary" role="button" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a class="btn btn-danger" role="button" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Excluir</a>
                        </div>
                    </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo!</h1>
    <p>Sistema de Crud - Contatos</p>
</div>

Views/Login/Index.cshtml
@using Projetos.CrudMvc.Models
@model LoginModel
@{
    Layout = "_LayoutDeslogado";
    ViewData["Title"] = "Login";
}

<form asp-controller="Login" asp-action="Entrar" method="post">
  <div class="form-group">
    <label for="exampleInputEmail1">Login</label>
    <input type="text" asp-for="Login" class="form-control" id="Login"  placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Senha</label>
    <input type="password" asp-for="Senha" class="form-control" id="Senha" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-primary m-3">Entrar</button>
</form>   

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/crudmvc.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crudmvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina
                                Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato"
                                asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario"
                                asp-action="Index">Usuários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - crudmvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

    

    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <script>
        $(document).ready(function () {

            $('.celular').mask('(00) 00000-0000');
        });
    </script>


</body>

</html>

Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/crudmvc.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">crudmvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - crudmvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

    

    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <script>
        $(document).ready(function () {

            $('.celular').mask('(00) 00000-0000');
        });
    </script>


</body>

</html>

Views/Usuario/ApagarConfirmacao.cshtml
@using Projetos.CrudMvc.Models;
@using crudmvc.Controllers;
@model UsuarioModel;

@{
    ViewData["Title"] = "Confirmação apagar o usuario";
}



<div class="text-center">
    <h3>Realmente deseja apagar o usuario (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger" role="button" asp-controller="Usuario" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a> 

Views/Usuario/Criar.cshtml
@using Projetos.CrudMvc.Enums
@using Projetos.CrudMvc.Models
@model UsuarioModel;
@{
    ViewData["Title"] = "Criar Usuário";
}

<div class="text-center">

    <h1>Cadastrar Usuário</h1>

    <form asp-controller="Usuario" asp-action="Criar" method="post">

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do usuário">
        </div>
        
        <div class="form-group">
            <label for="Email">E-mail</label>
            <input type="text" asp-for="Email"class="form-control" placeholder="Digite o e-mail do usuário">
        </div>

        <div class="form-group">
            <label for="Login">Login</label>
            <input type="text" asp-for="Login"class="form-control" placeholder="Digite o login do usuário">
        </div>

        <div class="form-group">
            <label for="Senha">Perfil</label>
            <select class="form-control" asp-for="Perfil">
                <option value="0">Selecione</option>
                <option value="@PerfilEnum.Adim">Administrado</option>
                <option value="@PerfilEnum.Padrao">Padrão</option>
            </select>
        </div>

        <div class="form-group">
            <label for="Senha">Senha</label>
            <input type="password" asp-for="Senha"class="form-control" placeholder="Digite a senha do usuário">
        </div>


        
        
        <button type="submit" class="btn btn-primary mt-2">Adicionar</button>
        <a class="btn btn-secondary mt-2" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a> 
        
    </form>

</div>

Views/Usuario/Editar.cshtml
@using Projetos.CrudMvc.Enums
@using Projetos.CrudMvc.Models;
@model UsuarioModel;
@{
    ViewData["Title"] = "Editar Usuario";
}

<div class="text-center">

    <h1>Editar Usuario</h1>

    <form asp-controller="Usuario" asp-action="Alterar" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do usuário">
        </div>

        <div class="form-group">
            <label for="Login">Login</label>
            <input type="text" asp-for="Login"class="form-control" placeholder="Digite o login do usuário">
        </div>
        
        <div class="form-group">
            <label for="Email">E-mail</label>
            <input type="text" asp-for="Email"class="form-control" placeholder="Digite o e-mail do usuário">
        </div>

        <div class="form-group">
            <label for="Senha">Perfil</label>
            <select class="form-control" asp-for="Perfil">
                <option value="0">Selecione</option>
                <option value="@PerfilEnum.Adim">Administrado</option>
                <option value="@PerfilEnum.Padrao">Padrão</option>
            </select>
        </div>


        
        
        <button type="submit" class="btn btn-primary mt-2">Editar</button>
        <a class="btn btn-secondary mt-2" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a> 
        
    </form>


</div>

Views/Usuario/Index.cshtml
@using Projetos.CrudMvc.Models;
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model List<UsuarioModel>;
@{
    ViewData["Title"] = "Listagem de Usuários";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Criar">Adicionar Novo Usuario</a>
    </div>
    <br>


    <h1>Listagem de Usuários</h1>

    <table class="table" id="table-usuarios">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">Email</th>
                <th scope="col">Perfil</th>
                <th scope="col">Data de Cadastro</th>
                <th scope="col">Botões</th>
            </tr>
        </thead>

        <tbody>
            @if (Model != null && Model.Any()){
                int cont = 0;
                foreach (UsuarioModel usuario in Model)
                {
                    cont ++; 
                    <tr>
                    <th scope="row">@cont</th>
                    <td>@usuario.Nome</td>
                    <td>@usuario.Login</td>
                    <td>@usuario.Email</td>
                    <td>@(usuario.Perfil == Projetos.CrudMvc.Enums.PerfilEnum.Adim ? "Administrador" : "Padão")</td>
                    <td>@usuario.DataCadastro</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-primary" role="button" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                            <a class="btn btn-danger" role="button" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Excluir</a>
                        </div>
                    </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>